dataset:
  dataset_dir: "/data"
  file_pattern: "phase_name/*/*/*/*.png"
  names_to_labels: ['negative', 'positive']
  num_samples: 36807
  num_classes: 2
  image_type: "png"
model:
  name: "mobilenetv2"

train:
  batch_size: 32
  optimizer_noun: "adam"
  learning_rate:
    initial: 0.0001
    decay_factor: 0.95
    before_decay: 2
  num_epochs: 100
  shuffle_buffer_size: 1024
  classification:
    classification_layers: null
    classification_type: "binary"