dataset:
  dataset_dir: "G:/rvl-cdip-jpeg"
  file_pattern: "labels/phase_name.txt"
  num_samples: 320000
  num_classes: 16
  image_type: "gray"
model:
  name: "mobilenet_v2"
  classification_layers: []
  classification_type: "multiclass"
  optimizer_noun: "adam"
  activation_func: "relu"
train:
  distribute: False
  xla : false
  batch_size: 16
  learning_rate:
    initial : 0.0001
    decay_factor : 0.95
    before_decay : 1
  num_epochs: 100
  shuffle_buffer_size: 512