dataset:
  dataset_dir: "D://MURA-v1.1"
  file_pattern: "phase_name//*//*//*//*.png"
  names_to_labels: {
                '0':'ELBOW_negative', 
                '1':'ELBOW_positive',
                '2':'FINGER_negative', 
                '3':'FINGER_positive',
                '4': 'FOREARM_negative',
                '5': 'FOREARM_positive',
                '6': 'HAND_negative',
                '7': 'HAND_positive',
                '8': 'HUMERUS_negative',
                '9': 'HUMERUS_positive',
                '10': 'SHOULDER_negative',
                '11': 'SHOULDER_positive',
                '12': 'WRIST_negative',
                '13': 'WRIST_positive'
                }
  num_samples: 36807
  num_classes: 2
  image_type: "png"
model:
  name: "mobilenetv2"

train:
  batch_size: 32
  optimizer_noun: "adam"
  learning_rate:
    initial: 0.0001
    decay_factor: 0.95
    before_decay: 2
  num_epochs: 100
  shuffle_buffer_size: 1024
  classification:
    classification_layers: null
    classification_type: "binary"